type EmployeeTestVariant {
  id: Int!
  title: String!
}

type EmployeeTestProcessMember {
  id: Int!
  employeeTestProcessId: Int!
  Emplouee: Employee!
}

type EmployeeTestProcess {
  id: Int!
  title: String!
  startDate: String!
  endDate: String
  EmployeeTestVariant: EmployeeTestVariant!
  EmplyeeProcessMembers: [EmployeeTestProcessMember!]!
  User: User!
  EmployeeTest: [EmployeeTest!]
}

type EmployeeTest {
  id: Int!
  startDate: String!
  endDate: String
  Emplouee: Employee!
  EmployeeTestAnswer: [EmployeeTestAnswer!]!
  EmployeeTestVariant: EmployeeTestVariant!
}

type EmployeeTestQuestion {
  id: Int!
  title: String!
  position: Int!
  EmployeeTestBlok: SimpleEmployeeTestBlock!
}

type EmployeeTestAnswer {
  id: Int!
  answer: String!
  EmployeeTestQuestion: EmployeeTestQuestion!
}

input CompleteEmployeeTestAnswer {
  questionId: Int!
  ans: Int!
}

type SimpleEmployeeTestBlock {
  id: Int!
  title: String!
  employeeTestVariantId: Int!
}

type EmployeeTestProcessResult {
  title: String!
  value: Float!
}
