type Token {
  token: String!
}

type LoginResponse {
  token: String!
}

type Query {
  # User #
  # TESTED
  getUsersRoles: [UserRole!]!
  getUsers: [User!]!
  getUser: User
  # ==== #

  # Student #
  # TESTED
  getStudentGroups: [StudentGroup!]!
  getStudents: [Student!]!
  # ======= #

  # Employee #
  # TESTED
  getEmployeePositions: [EmployeePosition!]!
  getEmployees: [Employee!]!
  # ======= #

  # Student test #
  # organizer
  # TESTED
  getStudentTestVariants: [StudentTestVariant!]!
  getStudentTestProcesses: [StudentTestProcessListItem!]!
  getStudentTestProcessMembers(
    studentTestProcessId: Int!
  ): [StudentTestProcessMembers!]!
  getStudentTestById(studentTestId: Int!): StudentTest

  # student
  # TESTED
  getAvailableStudentTestProcesses: [StudentTestProcessListItemWithStudentTest!]!
  getStudentTestQuestions(studentTestId: Int!): [StudentTestQuestion!]!
  # ============= #

  # Employee test #

  # Process
  getEmployeeTestVariants: [EmployeeTestVariant!]!
  getEmployeeTestProcesses: [EmployeeTestProcess!]!
  getEmployeeTestProcessById(processId: Int!): EmployeeTestProcess
  getAvailableEmployeeTestProcesses: [EmployeeTestProcess!]!
  getEmployeeTestProcessResults(processId: Int!): [EmployeeTestProcessResult!]!

  # Depricated
  getEmployeeTestByProcessId(processId: Int!): EmployeeTest
  getEmployeeTestById(testId: Int!): EmployeeTest

  # Test
  getEmployeeTestQuestions(testId: Int!): [EmployeeTestQuestion!]!
  # ============= #
}

type Mutation {
  # Auth #
  # TESTED
  login(login: String!, password: String!): LoginResponse
  # ==== #

  # User #
  # TESTED
  deleteUser(userId: Int!): Boolean!
  createUser(login: String!, password: String!, roleId: Int!): User!
  # ==== #

  # Student #
  # TESTED
  createStudentGroup(title: String!): StudentGroup!
  createStudent(
    passbookNumber: Int!
    name: String!
    groupId: Int!
    login: String!
    password: String!
  ): Student!

  # Потом
  deleteStudent(studentId: Int!): Boolean!
  # ==== #

  # Employee #
  # TESTED
  createEmployeePosition(title: String!): EmployeePosition!
  createEmployee(
    login: String!
    password: String!
    positionId: Int!
    name: String!
    email: String!
  ): Employee!

  # Потом
  deleteEmployee(employeeId: Int!): Boolean!
  # ==== #

  # Student test process #
  # TESTED
  startStudentTestProcess(
    studentTestVariantId: Int!
    title: String!
    studentPassbookNumbers: [Int!]!
  ): Boolean
  finishStudentTestProcess(studentTestProcessId: Int!): Boolean!

  #
  startStudentTest(studentTestProcessId: Int!): Int # ok
  answerStudentTestOne(
    studentTestId: Int!
    answers: [StudentTestOneAnswerInput!]!
  ): Boolean! # ok
  answerStudentTestTwo(
    studentTestId: Int!
    answers: [StudentTestTwoAnswerInput!]!
  ): Boolean! # ok
  answerStudentTestThree(studentTestId: Int!, fileBase64: String!): Boolean! # ok
  # ============ #

  # Employee test #

  # Process
  createEmployeeTestProcess(
    employeeIds: [Int!]!
    title: String!
    testVariantId: Int!
  ): EmployeeTestProcess
  finishEmployeeTestProcess(processId: Int!): Boolean!

  # Test
  startEmployeeTest(testProcessId: Int!): EmployeeTest
  answerEmployeeTest(
    testId: Int!
    answers: [CompleteEmployeeTestAnswer!]!
  ): Boolean!

  # Depricated
  finishEmployeeTest(testId: Int!): Boolean!

  # Depricated
  # answerEmployeeTest(testId: Int!, questionId: Int!, ans: Int!): Boolean!

  # ============= #
}
