export enum ServerExceptions {
  'RESULTS_IS_ALREADY_EXIST',
  'WRONG_PDF_FILE',
  'USER_IS_NOT_AUTHENTICATED',
  'USER_NOT_FOUND',
  'PASSWORD_IS_NOT_CORRECT',
  'USER_IS_ALREADY_EXIST',
  'NO_PERMISSION',
}
